//! Simulator Battle
//!
//! Pokemon Showdown - http://pokemonshowdown.com/
//!
//! This file is where the battle simulation itself happens.
//! The most important part of the simulation is the event system.

// Type modules
mod split_message;
mod arg;
mod event_listener;
mod effect_type;
mod effect;
mod custom_event_handler;
mod switch_result;
mod event_info;
mod faint_data;
mod battle_options;
mod player_options;
mod team_format;
mod battle_request_state;
mod priority_item;
mod spread_move_hit_result;
mod battle_struct;

// Function modules
mod new;
mod pokemon_at;
mod pokemon_at_mut;
mod set_player;
mod get_team;
mod start;
mod random;
mod random_chance;
mod sample;
mod get_side;
mod get_side_mut;
mod p1;
mod p2;
mod get_all_active;
mod check_win;
mod next_effect_order;
mod init_effect_state;
mod choose;
mod get_log;
mod make_choices;
mod commit_choices;
mod compare_action_priority;
mod insert_run_switch_action;
mod insert_field_action;
mod queue_insert_choice;
mod field_event_switch_in;
mod get_move_target;
mod faint_messages;
mod debug;
mod extract_channel_messages;
mod get_debug_log;
mod add;
mod add_move;
mod add_side_condition;
mod call_duration_callback;
mod hint;
mod trunc;
mod chain;
mod chain_f;
mod modify;
mod modify_tuple;
mod modify_f;
mod clamp_int_range;
mod event_modifier;
mod tie;
mod win;
mod lose;
mod force_win;
mod set_active_move;
mod clear_active_move;
mod modify_active_move;
mod suppressing_ability;
mod get_all_pokemon;
mod is_adjacent;
mod is_ally;
mod is_pokemon_fainted;
mod get_random_target;
mod update_speed;
mod damage;
mod decrement_active_move_actions;
mod direct_damage;
mod heal;
mod boost;
mod faint;
mod check_fainted;
mod compare_priority;
mod compare_redirect_order;
mod compare_left_to_right_order;
mod speed_sort;
mod sort_action_queue;
mod shuffle_range;
mod get_pokemon;
mod get_pokemon_mut;
mod can_switch;
mod get_random_switchable;
mod possible_switches;
mod valid_target_loc;
mod valid_target;
mod get_at_slot;
mod end_turn;
mod turn_loop;
mod run_action;
mod all_choices_done;
mod check_move_makes_contact;
mod get_action_speed;
mod get_pokemon_action_speed;
mod get_pokemon_stat;
mod swap_position;
mod get_category;
mod clear_request;
mod make_request;
mod maybe_trigger_endless_battle_clause;
mod restart;
mod reset_rng;
mod join;
mod destroy;
mod single_event;
mod single_event_side;
mod get_effect_type;
mod dispatch_single_event;
mod handle_ability_event;
mod handle_item_event;
mod handle_move_event;
mod handle_condition_event;
mod run_event;
mod with_effect_state;
mod find_event_handlers;
mod priority_event;
mod get_event_modifier;
mod get_move_hit_data;
mod set_event_modifier;
mod randomizer;
mod each_event;
mod get_target;
mod get_at_loc;
mod undo_choice;
mod spread_damage;
mod final_modify;
mod modify_internal;
mod add_split;
mod attr_last_move;
mod chain_modify;
mod chain_modify_fraction;
mod check_ev_balance;
mod clear_effect_state;
mod debug_error;
mod field_event;
mod get_callback;
mod has_callback;
mod get_overflowed_turn_count;
mod get_requests;
mod resolve_priority;
mod retarget_last_move;
mod run_pick_team;
mod send_updates;
mod set_trapped;
mod set_weather;
mod set_terrain;
mod clear_weather;
mod clear_terrain;
mod effective_weather;
mod suppressing_weather;
mod is_weather;
mod is_terrain;
mod remove_pseudo_weather;
mod remove_slot_condition;
mod add_slot_condition;
mod add_pseudo_weather;
mod show_open_team_sheets;
mod spread_modify;
mod stat_modify;
mod tiebreak;
mod to_json;
mod find_battle_event_handlers;
mod find_field_event_handlers;
mod find_side_event_handlers;
mod find_pokemon_event_handlers;
mod get_type_effectiveness_mod;
mod on_event;
mod on_event_priority;
mod run_custom_event_handlers;
mod use_move;

// Re-export types from submodules
pub use split_message::SplitMessage;
pub use arg::Arg;
pub use event_listener::EventListener;
pub use effect_type::EffectType;
pub use effect::Effect;
pub use custom_event_handler::{CustomEventHandler, EventCallback};
pub use switch_result::SwitchResult;
pub use event_info::EventInfo;
pub use faint_data::FaintData;
pub use battle_options::BattleOptions;
pub use player_options::PlayerOptions;
pub use team_format::TeamFormat;
pub use battle_request_state::BattleRequestState;
pub use priority_item::PriorityItem;
pub use spread_move_hit_result::SpreadMoveHitResult;
pub use battle_struct::Battle;
