//! Simulator Pokemon
//!
//! Pokemon Showdown - http://pokemonshowdown.com/
//!
//! This module contains the Pokemon struct and related types.

// Type modules
mod move_slot;
mod attacker;
mod pokemon_set;
mod trapped_state;
mod pokemon_struct;
mod get_move_targets_result;
mod move_hit_data;

// Function modules
mod new;
mod update_move_pp;
mod fullname;
mod details;
mod is_fainted;
mod get_health;
mod take_damage;
mod heal;
mod set_status;
mod cure_status;
mod has_status;
mod add_volatile;
mod remove_volatile;
mod has_volatile;
mod get_volatile;
mod get_volatile_mut;
mod clear_volatiles;
mod get_stat;
mod boost;
mod clear_boosts;
mod update_speed;
mod clear_turn_state;
mod clear_switch_state;
mod get_slot;
mod can_switch;
mod get_move_pp;
mod deduct_pp;
mod set_pp;
mod has_move;
mod get_types;
mod is_grounded;
mod is_semi_invulnerable;
mod is_protected;
mod effective_weather;
mod has_item;
mod has_ability;
mod copy_volatile_from;
mod get_weight;
mod set_type;
mod add_type;
mod positive_boosts;
mod get_action_speed;
mod disable_move;
mod get_usable_moves;
mod can_tera;
mod terastallize;
mod get_updated_details;
mod calculate_stat;
mod get_best_stat;
mod has_type;
mod faint;
mod damage;
mod is_ally;
mod is_adjacent;
mod get_capped_boost;
mod boost_by;
mod set_boost;
mod clear_ability;
mod set_ability;
mod get_ability;
mod clear_item;
mod set_item;
mod take_item;
mod get_item;
mod set_hp;
mod move_used;
mod is_last_active;
mod ignoring_ability;
mod ignoring_item;
mod update_max_hp;
mod is_sky_dropped;
mod get_move_data;
mod get_move_data_mut;
mod get_undynamaxed_hp;
mod try_trap;
mod got_attacked;
mod get_locked_move;
mod max_move_disabled;
mod transform_into;
mod set_species;
mod forme_change;
mod get_base_species_name;
mod get_base_species_base_species;
mod get_forme;
mod get_base_species_num;
mod get_moves;
mod get_base_moves;
mod to_json;
mod get_combat_power;
mod get_loc_of;
mod get_at_loc;
mod get_smart_targets;
mod get_last_attacked_by;
mod get_last_damaged_by;
mod get_dynamax_request;
mod get_move_request_data;
mod get_switch_request_data;
mod try_set_status;
mod use_item;
mod eat_item;
mod run_effectiveness;
mod run_immunity;
mod run_status_immunity;
mod remove_linked_volatiles;
mod clear_volatile;
mod get_nature;
mod get_status;
mod destroy;
mod allies;
mod allies_and_self;
mod adjacent_allies;
mod foes;
mod adjacent_foes;
mod clear_status;
mod get_move_hit_data;
mod get_move_targets_stub;

// Re-export types from submodules
pub use move_slot::MoveSlot;
pub use attacker::Attacker;
pub use pokemon_set::PokemonSet;
pub use trapped_state::TrappedState;
pub use pokemon_struct::Pokemon;
pub use get_move_targets_result::GetMoveTargetsResult;
pub use move_hit_data::MoveHitData;
